// Generated by CoffeeScript 1.6.1
(function() {

  window.YakShave = new Backbone.Marionette.Application();

  YakShave.addRegions({
    main: '#content'
  });

  YakShave.on('initalize:after', function() {
    return Backbone.history.start();
  });

  YakShave.addInitializer(function() {
    var bigYakView;
    bigYakView = new YakShave.BigYakView({
      model: new Backbone.Model({
        image_path: "images/yak.png"
      })
    });
    return YakShave.main.show(bigYakView);
  });

  $(document).ready(function() {
    return YakShave.start();
  });

}).call(this);
